export default {
  id: "cursor",
  priority: 50,
  alias: "cu",
  uiAlias: "cu",
  display: {
    name: "Cursor IDE",
    icon: "edit_note",
    color: "#00D4AA",
    website: "https://cursor.com",
    notice: {
      signupUrl: "https://cursor.com",
    },
  },
  category: "oauth",
  transport: {
    baseUrl: "https://api2.cursor.sh",
    chatPath: "/aiserver.v1.ChatService/StreamUnifiedChatWithTools",
    format: "cursor",
    headers: {
      "connect-accept-encoding": "gzip",
      "connect-protocol-version": "1",
      "Content-Type": "application/connect+proto",
      "User-Agent": "connect-es/1.6.1",
    },
    clientVersion: "3.12.17",
    usage: {
      url: "https://api2.cursor.sh/aiserver.v1.DashboardService/GetCurrentPeriodUsage",
      planInfoUrl: "https://api2.cursor.sh/aiserver.v1.DashboardService/GetPlanInfo",
    },
  },
  models: [
    { id: "default", name: "Auto (Server Picks)" },
    { id: "claude-4.5-opus-high-thinking", name: "Claude 4.5 Opus High Thinking" },
    { id: "claude-4.5-opus-high", name: "Claude 4.5 Opus High" },
    { id: "claude-4.5-sonnet-thinking", name: "Claude 4.5 Sonnet Thinking" },
    { id: "claude-4.5-sonnet", name: "Claude 4.5 Sonnet" },
    { id: "claude-4.5-haiku", name: "Claude 4.5 Haiku" },
    { id: "claude-4.5-opus", name: "Claude 4.5 Opus" },
    { id: "gpt-5.2-codex", name: "GPT 5.2 Codex" },
    { id: "claude-4.6-opus-max", name: "Claude 4.6 Opus Max" },
    { id: "claude-4.6-sonnet-medium-thinking", name: "Claude 4.6 Sonnet Medium Thinking" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "gemini-3-flash-preview", name: "Gemini 3 Flash Preview" },
    { id: "gpt-5.2", name: "GPT 5.2" },
    { id: "gpt-5.3-codex", name: "GPT 5.3 Codex" },
  ],
  oauth: {
    apiEndpoint: "https://api2.cursor.sh",
    chatEndpoint: "/aiserver.v1.ChatService/StreamUnifiedChatWithTools",
    modelsEndpoint: "/agent.v1.AgentService/GetUsableModels",
    api3Endpoint: "https://api3.cursor.sh",
    agentEndpoint: "https://agent.api5.cursor.sh",
    agentNonPrivacyEndpoint: "https://agentn.api5.cursor.sh",
    clientVersion: "3.12.17",
    clientType: "ide",
    loginUrl: "https://cursor.com/loginDeepControl",
    pollUrl: "https://api2.cursor.sh/auth/poll",
    refreshUrl: "https://api2.cursor.sh/oauth/token",
    // Cursor IDE public OAuth client used for the refresh_token grant; live-verified 2026-09-25.
    refreshClientId: "KbZUR41cY7W6zRSdpSUJ7I7mLYBKOCmB",
    // Tokens are ~60-day session JWTs; refresh a day early so sleeping hosts don't miss it.
    refreshLeadMs: 86_400_000,
    dbKeys: {
      accessToken: "cursorAuth/accessToken",
      refreshToken: "cursorAuth/refreshToken",
      machineId: "storage.serviceMachineId",
    },
  },
  features: {
    usage: true,
    liveModels: true,
  },
};
